version: "3.7"
services:
  HowToGraphQLDB:
    image: "mysql:8.0"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=HowToGraphQLDB"
      - "MYSQL_USER=howtouser"
      - "MYSQL_PASSWORD=howtopassword"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - ./mysqldata:/var/lib/mysql